mtn:
  sandbox:
    apiUserId: bd9d6825-bc2f-4dbe-b357-c9bf47c3dc16
    apiKey: 23712f2c7be54b879ecd17a333b0c6cf
    targetEnvironment: sandbox
    baseUrl: https://sandbox.momodeveloper.mtn.com/disbursement
    subscriptionKey: b88dfe2c8565489a9747f57eda401efd

server:
  port: 8082

spring:
  application:
    name: dispatcher

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: dispatcher-group
      auto-offset-reset: earliest
    producer:
      retries: 3
      acks: all

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.kafka: INFO
    org.springframework.web.reactive: INFO
