mtn:
  sandbox:
    apiUserId: bd9d6825-bc2f-4dbe-b357-c9bf47c3dc16
    apiKey: 23712f2c7be54b879ecd17a333b0c6cf
    targetEnvironment: sandbox
    baseUrl: https://sandbox.momodeveloper.mtn.com/disbursement
    subscriptionKey: b88dfe2c8565489a9747f57eda401efd

telecel:
  sandbox:
    apiKey: dqlOZQ0JYsHQvipUiac3r9gZo2A8Isk1
    publicKey: MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAszE+xAKVB9HRarr6/uHYYAX/RdD6KGVIGlHv98QKDIH26ldYJQ7zOuo9qEscO0M1psSPe/67AWYLEXh13fbtcSKGP6WFjT9OY6uV5ykw9508x1sW8UQ4ZhTRNrlNsKizE/glkBfcF2lwDXJGQennwgickWz7VN+AP/1c4DnMDfcl8iVIDlsbudFoXQh5aLCYl+XOMt/vls5a479PLMkPcZPOgMTCYTCE6ReX3KD2aGQ62uiu2T4mK+7Z6yvKvhPRF2fTKI+zOFWly//IYlyB+sde42cIU/588msUmgr3G9FYyN2vKPVy/MhIZpiFyVc3vuAAJ/mzue5p/G329wzgcz0ztyluMNAGUL9A4ZiFcKOebT6y6IgIMBeEkTwyhsxRHMFXlQRgTAufaO5hiR/usBMkoazJ6XrGJB8UadjH2m2+kdJIieI4FbjzCiDWKmuM58rllNWdBZK0XVHNsxmBy7yhYw3aAIhFS0fNEuSmKTfFpJFMBzIQYbdTgI28rZPAxVEDdRaypUqBMCq4OstCxgGvR3Dy1eJDjlkuiWK9Y9RGKF8HOI5a4ruHyLheddZxsUihziPF9jKTknsTZtF99eKTIjhV7qfTzxXq+8GGoCEABIyu26LZuL8X12bFqtwLAcjfjoB7HlRHtPszv6PJ0482ofWmeH0BE8om7VrSGxsCAwEAAQ==
    baseUrl: https://uat.openapi.m-pesa.com/sandbox/ipg/v2/vodafoneGHA
    

server:
  port: 8082

spring:
  application:
    name: dispatcher

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: dispatcher-group
      auto-offset-reset: earliest
    producer:
      retries: 3
      acks: all

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.kafka: INFO
    org.springframework.web.reactive: INFO
